version: '3.4'

services:
  mon:
    build: .
    tty: true
    stdin_open: true
    command: npm run mon -- -L
    volumes:
      - ./:/usr/src/app
  debug:
    build: .
    tty: true
    stdin_open: true
    command: npm run debug -- -L
    ports:
      - 9229:9229
    volumes:
      - ./:/usr/src/app
  test:
    build: .
    command: npm test
    volumes:
      - ./:/usr/src/app
  # db:
  #   image: mysql:latest